# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 669822a77cd894a710c33a59c7d1ea50294effa9fc3b3d27127c2ebc52a403bd043ad7a1beecf9a235d3176494a93ee7b21b1644db1eec9330a4fe510f33fac8

test:
  secret_key_base: 5d3a49b3c2414ad61fb6fdacd77b447d3226cf58cc4c185f72b6b93f8bb44325ab09b474686ac36d071498eedd2d28a1c8a9af02685d12298a307059e988d71f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
